# Generated by Django 3.2.5 on 2021-07-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.diner')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_date', models.DateField(auto_now_add=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('diner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.diner')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('diner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.diner')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.dish')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
